name: CI  main 

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image tag from latest dev run
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci-dev.yml
          branch: dev
          name: image-tag
          workflow_conclusion: success

      - name: Read image SHA
        id: tag
        run: |
          SHA=$(cat image-tag.txt)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Promoting image: $SHA"

      #upadtes manifest with new image tag

